# Generated by Django 3.0.6 on 2020-05-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='kind',
            field=models.CharField(choices=[('초등학교', '초등학교'), ('중학교', '중학교'), ('고등학교', '고등학교')], max_length=4),
        ),
    ]
